name: Sizer
main: CapricornOfLynx\Sizer\loader
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
version: 2.2.5
authors: [CapricornOfLynx, DokiaCraft]
website: http://dokiacraft.net/
permissions:
    player.size:
        default: op
